### PR TITLE
Fix #312

### LINKED ISSUE #312: f18 cannot be built with gcc 7.3.0 anymore, please update readme file
After pulling recent changes I can't build f18 with gcc 7.3.0 anymore. I can build it with gcc 8.2 and Clang/LLVM 7.

```
[ 34%] Building CXX object lib/evaluate/CMakeFiles/FortranEvaluate.dir/intrinsics.cc.o
cd build-shared-gcc/lib/evaluate && /usr/bin/g++-7.3.0  -DFortranEvaluate_EXPORTS -I../f18/include -Ibuild-shared-gcc/include -I/usr/lib/llvm/7/include  -std=c++17 -Wall -pedantic -O2 -g -DNDEBUG -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -o CMakeFiles/FortranEvaluate.dir/intrinsics.cc.o -c lib/evaluate/intrinsics.cc
In file included from /usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/vector:62:0,
                 from /usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/functional:61,
                 from lib/evaluate/../common/idioms.h:32,
                 from lib/evaluate/../common/Fortran.h:21,
                 from lib/evaluate/common.h:18,
                 from lib/evaluate/call.h:18,
                 from lib/evaluate/intrinsics.h:18,
                 from lib/evaluate/intrinsics.cc:15:
/usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/bits/stl_construct.h: In instantiation of âvoid std::_Construct(_T1*, _Args&& ...) [with _T1 = std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn>; _Args = {const std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn>&}]â:
/usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/bits/stl_uninitialized.h:83:18:   required from âstatic _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn>*, std::vector<std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn> > >; _ForwardIterator = std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn>*; bool _TrivialValueTypes = false]â
/usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/bits/stl_uninitialized.h:134:15:   required from â_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn>*, std::vector<std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn> > >; _ForwardIterator = std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn>*]â
/usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/bits/stl_uninitialized.h:289:37:   required from â_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn>*, std::vector<std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn> > >; _ForwardIterator = std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn>*; _Tp = std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn>]â
/usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/bits/stl_vector.h:331:31:   required from âstd::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn>; _Alloc = std::allocator<std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn> >]â
lib/evaluate/characteristics.h:87:8:   required from âconstexpr std::_Optional_payload<_Tp, false, false>::_Optional_payload(std::in_place_t, _Args&& ...) [with _Args = {Fortran::evaluate::UnrestrictedSpecificIntrinsicFunctionInterface&}; _Tp = Fortran::evaluate::UnrestrictedSpecificIntrinsicFunctionInterface]â
/usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/optional:324:38:   required from âconstexpr std::_Optional_base<_Tp>::_Optional_base(std::in_place_t, _Args&& ...) [with _Args = {Fortran::evaluate::UnrestrictedSpecificIntrinsicFunctionInterface&}; typename std::enable_if<is_constructible_v<_Tp, _Args&& ...>, bool>::type <anonymous> = 0; _Tp = Fortran::evaluate::UnrestrictedSpecificIntrinsicFunctionInterface]â
/usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/optional:492:54:   required from âconstexpr std::optional<_Tp>::optional(_Up&&) [with _Up = Fortran::evaluate::UnrestrictedSpecificIntrinsicFunctionInterface&; typename std::enable_if<std::__and_<std::__not_<std::is_same<std::optional<_Tp>, typename std::decay<_U1>::type> >, std::__not_<std::is_same<std::in_place_t, typename std::decay<_U1>::type> >, std::is_constructible<_Tp, _Up&&>, std::is_convertible<_Up&&, _Tp> >::value, bool>::type <anonymous> = 1; _Tp = Fortran::evaluate::UnrestrictedSpecificIntrinsicFunctionInterface]â
lib/evaluate/intrinsics.cc:1308:14:   required from here
/usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/bits/stl_construct.h:75:7: error: use of deleted function âstd::variant<_Types>::variant(const std::variant<_Types>&) [with _Types = {Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn}]â
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from lib/evaluate/../common/idioms.h:38:0,
                 from lib/evaluate/../common/Fortran.h:21,
                 from lib/evaluate/common.h:18,
                 from lib/evaluate/call.h:18,
                 from lib/evaluate/intrinsics.h:18,
                 from lib/evaluate/intrinsics.cc:15:
/usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/variant:939:7: note: âstd::variant<_Types>::variant(const std::variant<_Types>&) [with _Types = {Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn}]â is implicitly deleted because the default definition would be ill-formed:
       variant(const variant&) = default;
       ^~~~~~~
/usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/variant:939:7: error: use of deleted function âconstexpr std::_Enable_copy_move<false, false, true, true, _Tag>::_Enable_copy_move(const std::_Enable_copy_move<false, false, true, true, _Tag>&) [with _Tag = std::variant<Fortran::evaluate::characteristics::DummyDataObject, Fortran::evaluate::characteristics::DummyProcedure, Fortran::evaluate::characteristics::AlternateReturn>]â
In file included from /usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/optional:43:0,
                 from /usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/bits/node_handle.h:39,
                 from /usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/bits/hashtable.h:37,
                 from /usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/unordered_map:47,
                 from /usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/functional:60,
                 from lib/evaluate/../common/idioms.h:32,
                 from lib/evaluate/../common/Fortran.h:21,
                 from lib/evaluate/common.h:18,
                 from lib/evaluate/call.h:18,
                 from lib/evaluate/intrinsics.h:18,
                 from lib/evaluate/intrinsics.cc:15:
/usr/lib/gcc/aarch64-unknown-linux-gnu/7.3.0/include/g++-v7/bits/enable_special_members.h:157:15: note: declared here
     constexpr _Enable_copy_move(_Enable_copy_move const&) noexcept  = delete;
               ^~~~~~~~~~~~~~~~~
make[2]: *** [lib/evaluate/CMakeFiles/FortranEvaluate.dir/build.make:279: lib/evaluate/CMakeFiles/FortranEvaluate.dir/intrinsics.cc.o] Error 1
make[2]: Leaving directory 'build-shared-gcc'
make[1]: *** [CMakeFiles/Makefile2:251: lib/evaluate/CMakeFiles/FortranEvaluate.dir/all] Error 2
make[1]: Leaving directory 'build-shared-gcc'
make: *** [Makefile:95: all] Error 2
```

### PR DESCRIPTION
**Pull request by klausler**
Add optional copy construction and assignment to `OwningPointer`, which is useful in itself and also dodges a possibly bogus build-time error from g++ 7.x.

### CODE REVIEW

File: lib/evaluate/expression.h [hunk 1]
```diff
@@ -762,7 +762,7 @@ template<> class Expr<SomeType> : public ExpressionBase<SomeType> {
 };
 
 // This wrapper class is used, by means of a forward reference with
-// OwningPointer, to implement owning pointers to analyzed expressions
+// OwningPointer , to implement owning pointers to analyzed expressions
```
Comment (tskeith) [inline lib/evaluate/expression.h]: This looks like an accident.
