### PR TITLE
Prevent RESULT name from being the same as the function name

### LINKED ISSUE #726: Regression: internal error when `RESULT()` has same name as function
```
integer function f() result(f)
  f = 0
end
```

elicits `error: Internal: no symbol found for 'f'` with the caret pointing at the `f` in `result(f)`.

### PR DESCRIPTION
**Pull request by jeanPerier**
Fix #726.
Check and emit error message for such scenario. Also set error on the result symbol because it is unclear what it is inside the function.

### CODE REVIEW

File: lib/semantics/resolve-names.cc [hunk 1]
```diff
@@ -2483,6 +2483,13 @@ void SubprogramVisitor::Post(const parser::FunctionStmt &stmt) {
   funcResultDetails.set_funcResult(true);
   funcInfo_.resultSymbol =
       &MakeSymbol(*funcResultName, std::move(funcResultDetails));
+  if (funcInfo_.resultName && funcInfo_.resultName->source == name.source) {
+    // C1560. TODO also enforce on entry names when entry implemented
+    Say(funcInfo_.resultName->source,
+        "'%s' is already the function name and cannot appear in RESULT"_err_en_US,
```
Comment (klausler) [inline lib/semantics/resolve-names.cc]: I would emit a warning, not an error, and ignore the `RESULT` name.

Comment (jeanPerier) [reply lib/semantics/resolve-names.cc]: OK, pgfortran is accepting this (none of the other tested compilers do) and I do not see issues that could come from relaxing the constraint.
I have transformed the error into a warning that states that references to `f` inside the function scope will be considered references to the result only.
