### PR TITLE
Fix issues #517, #518, and 546

### LINKED ISSUE #517: Label missing in unparsed output after semantics
```
  do 1 i=1,2
    goto 2
1 continue
2 do 3 i=1,2
3 continue
  end
```

loses the label `2` in the unparsed output if semantics is enabled.

### PR DESCRIPTION
**Pull request by jeanPerier**
Fixes #517, #518, and #546:
- Only allow out-of-scope label target for label-do-stmt when the label is on an end-stmt of a scope directly nested into the one of the label-do-stmt.
- Also transform label-do-stmt into non-label-do constructs in such out-of-scope cases so that later phases do not have to handle label-do-stmt.

This PR makes out-of-scope labels more restrictive, e.g, the following is not allowed anymore by label resolution:
```
do 1 i=1,10
 if (i>5) then
1  print*, i
 end if
end
```
but the following remains OK with a warning:
```
do 1 i=1,10
  if (i>5) then
    print*, i
1 end if
end
```
and is now transformed into
```
do  i=1,10
  if (i>5) then
    print*, i
1 end if
end do
end
```
This is done with if, do and select end statements.
This seems to be in line with what pgfortran and NAG are accepting (select type and rank end statements are also accepted, this is to avoid making resolve-labels.cc much more complex). 

Edit: fix for #517 added in later commit because it was small enough

### CODE REVIEW

File: lib/semantics/resolve-labels.cc [hunk 1]
```diff
@@ -889,9 +907,16 @@ void CheckLabelDoConstraints(const SourceStmtList &dos,
...
     } else if (!InInclusiveScope(scopes, scope, doTarget.proxyForScope)) {
       // C1133
-      errorHandler.Say(position,
-          parser::MessageFormattedText{
-              "label '%u' is not in scope"_en_US, SayLabel(label)});
+      if (doTarget.legacyAcceptedInDirectSubscope &&
+          ParentScope(scopes, doTarget.proxyForScope) == scope) {
+        errorHandler.Say(doTarget.parserCharBlock,
+            parser::MessageFormattedText{
+                "A DO loop should terminate with an END DO or CONTINUE inside its scope"_en_US});
```
Comment (schweitzpgi) [inline lib/semantics/resolve-labels.cc]: Can this case be merged with the succeeding `else if` case rather than replicating the message?

File: lib/semantics/resolve-labels.cc [hunk 2]
```diff
@@ -209,6 +210,14 @@ const parser::CharBlock *GetStmtName(const parser::Statement<A> &stmt) {
   return nullptr;
 }
 
+template<typename A>
+static constexpr bool LabelDoTargetAcceptedInDirectSubscopeOn(
+    const parser::Statement<A> &statement) {
+  return (std::is_same_v<A, parser::EndIfStmt> ||
```
Comment (klausler) [inline lib/semantics/resolve-labels.cc]: Needless parentheses; could also be written by defining a `std::tuple<>` of these types and using `common::HasMember`.

File: lib/semantics/canonicalize-do.cc [hunk 3]
```diff
@@ -33,6 +33,30 @@ class CanonicalizationOfDoLoops {
...
+                          caseConstruct.value().t));
+                },
+                [&](common::Indirection<SelectRankConstruct> &selectRank) {
+                  CanonicalizeIfMatch(block, stack, i,
+                      std::get<Statement<EndSelectStmt>>(selectRank.value().t));
+                },
+                [&](common::Indirection<SelectTypeConstruct> &selectType) {
+                  CanonicalizeIfMatch(block, stack, i,
+                      std::get<Statement<EndSelectStmt>>(selectType.value().t));
+                },
```
Comment (klausler) [inline lib/semantics/canonicalize-do.cc]: Also `associate`, `block`, `forall`, `where`. and `critical`, maybe more.

File: lib/semantics/resolve-labels.cc (hunk 1 above)
Comment (jeanPerier) [reply lib/semantics/resolve-labels.cc]: Thanks, it saves some lines and the merged conditions remain readable.

File: lib/semantics/resolve-labels.cc (hunk 2 above)
Comment (jeanPerier) [reply lib/semantics/resolve-labels.cc]: Thanks, that makes even more sens now that there are more `End..Stmt` to handle.

File: lib/semantics/canonicalize-do.cc (hunk 3 above)
Comment (jeanPerier) [reply lib/semantics/canonicalize-do.cc]: OK, I only took the f95 executable constructs (+ `select type` and `select rank`, because they were "dragged" by `select case` support for simplicity), the rest was rejected by resolve-labels.cc. However, it seems more consistent to accept it on all executable construct end statements (+ forall and where end statements) (pgfortran does so for all the ones it supports).

I have added the suggested plus `change team` and renamed the functions/variables accordingly.

I also added a non-standard feature to control warning on label do loops terminating at statements different than `end do` or `continue`. I can revert this last commit if you think it is not justified.

File: test/semantics/label14.f90 [hunk 4]
```diff
@@ -13,22 +13,121 @@
...
+
+subroutine foo0()
   do 1 j=1,2
     if (.true.) then
+! CHECK: A DO loop should terminate with an END DO or CONTINUE
 1   end if
   do 2 k=1,2
     do i=3,4
       print*, i+k
+! CHECK: A DO loop should terminate with an END DO or CONTINUE
```
Comment (tskeith) [inline test/semantics/label14.f90]: I think this test will pass if the message comes out once anywhere in the source. It's not checking that the error is emitted for each place the CHECK comment appears.

It would be a better test if it were split into separate source files, each with one error. Or better yet, switch to using test_errors.sh.

File: lib/semantics/canonicalize-do.cc [hunk 5]
```diff
@@ -34,16 +34,34 @@ class CanonicalizationOfDoLoops {
             common::visitors{
                 [](auto &) {},
                 // Labels on end-stmt of constructs are accepted by f18 for
```
Comment (tskeith) [inline lib/semantics/canonicalize-do.cc]: The "for" at the end of this line is left over from the previous version of the comment and should be removed.

Comment (jeanPerier) [reply lib/semantics/canonicalize-do.cc]: Thanks, fixed.

File: test/semantics/label14.f90 (hunk 4 above)
Comment (jeanPerier) [reply test/semantics/label14.f90]: Thanks, it was indeed not testing as I intended.
I tried using `test_errors.sh` with `-Mstandard -Werror` but that did not work because `-Werror` does not add the `error:` prefix to warnings (which I think is correct, but annoying in this case).
So I went the other way you suggested and split the tests into different sources. To make it more valuable, I also added checks to test if the label-do were rewritten as non-label-do.
