### PR TITLE
Avoid interference between different construct association in name resolutions

### LINKED ISSUE #598: Bogus error from sourced allocation
```
type t1
end type
type, extends(t1) :: t2
end type
class(t2), allocatable :: x
class(*), allocatable :: a
allocate(t2::a)
select type(a)
  type is(t2)
     associate(y=>a%t1)
     end associate
end select
select type(a)
  class is (t2)
    allocate(x,source=a)
end select
end
```

produces `bug.f90:15:14: error: Allocatable object in ALLOCATE must be type compatible with source expression from MOLD or SOURCE` on the sourced allocation.

The previous `select type` and its nested `associate` constructs need to be present to demonstrate the bug.  `valgrind`, however, does not complain about uninitialized data usage.

### PR DESCRIPTION
**Pull request by jeanPerier**
Fix #598 and similar issues.
Transform `resolve-names.cc` `ConstructVisitor` `association_` member into a stack so that different association construct (select-type, select-rank, change-team, associate) imbrication/succession do not interfere with each other leading to erroneous symbol resolution.

### CODE REVIEW

File: lib/semantics/resolve-names.cc [hunk 1]
```diff
@@ -4407,6 +4440,20 @@ ConstructVisitor::Selector ConstructVisitor::ResolveSelector(
       x.u);
 }
 
+ConstructVisitor::Association &ConstructVisitor::GetCurrentAssociation() {
+  CHECK(associationStack_.size());
```
Comment (klausler) [inline lib/semantics/resolve-names.cc]: `!associationStack_.empty()` makes the condition clearer.  Also below.
