### PR TITLE
Detect incorrect use of assumed-type dummy arguments

### LINKED ISSUE #915: CHECK fails on call to Fortran::semantics::GetExpr
Here's the Fortran source:
subroutine s1()

  type(*)  :: x
  y = x

end subroutine s1

The compiler generates the following parse tree for the expression "x" in the assignment statement:
| | | Expr -> Designator -> DataRef -> Name = 'x'

I added the following code to the compiler:

void DoChecker::Leave(const parser::Expr &parserExpr) {
    if (const auto *expr{GetExpr(parserExpr)}) {

The call to "GetExpr()" fails in the following CHECK in lib/semantics/tools.h:

struct GetExprHelper {
  const SomeExpr *Get(const parser::Expr::TypedExpr &x) {
    CHECK(x);
    return x && x->v ? &*x->v : nullptr;
  }
I can avoid this problem by testing parserExpr.typedExpr before making the call to GetExpr(), but I'm concerned that there's some other potential problem that I'll be covering over by doing this.

### PR DESCRIPTION
**Pull request by tskeith**
Assumed-type dummy arguments can only be used as actual arguments. If
they are used in other contexts it is an error. Change argument analysis
to handle these differently depending on the context. `allowAssumedType`
is set when the argument can be assumed-type. These expressions now all
get `typedExpr` set to `nullopt`.

Change `AnalyzeSectionSubscripts` to analyze all of the subscripts
even if one has an error. This ensures they all get analyzed expressions
(or `nullopt` in case of error).

Fix a bug analyzing `BoundsRemapping`: the lower bound was analyzed
twice and the upper bound not at all.

These change mean that `typedExpr` is set in all known cases.
Fixes #915.

### CODE REVIEW

File: lib/semantics/expression.cc [hunk 1]
```diff
@@ -134,6 +134,7 @@ class ArgumentAnalyzer {
   ArgumentAnalyzer(ExpressionAnalyzer &context, parser::CharBlock source)
     : context_{context}, source_{source} {}
   bool fatalErrors() const { return fatalErrors_; }
+  void set_allowAssumedType(bool x = true) { allowAssumedType_ = x; }
```
Comment (klausler) [inline lib/semantics/expression.cc]: This flag appears to be only set after construction in the two cases of function and subroutine references, and never cleared, so it could be specified with an additional Boolean argument to the second constructor, and also made a `const` data member.

Comment (tskeith) [reply lib/semantics/expression.cc]: OK, good idea.
